# Generated by Django 3.2.25 on 2024-08-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('linkedin_link', models.TextField(blank=True, null=True)),
                ('insta_link', models.TextField(blank=True, null=True)),
                ('github_link', models.TextField(blank=True, null=True)),
                ('whatsapp_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
