# Generated by Django 3.2.25 on 2024-08-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='whatsapp_link',
            new_name='whatsapp_No',
        ),
    ]
