# Generated by Django 3.2.25 on 2024-08-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_auto_20240809_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktop_img',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='mobile_img',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='desktop_img',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='desktop_img',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='mobile_img',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='mobile_img',
            name='image3',
        ),
    ]
