# Generated by Django 3.2.25 on 2024-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20240809_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='nam',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
