# Generated by Django 3.2.25 on 2024-08-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_footer_nam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='nam',
            new_name='name',
        ),
    ]
