# Generated by Django 3.2.25 on 2024-08-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0012_alter_education_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Degree',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
