# Generated by Django 3.2.25 on 2024-08-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0016_skill_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='list',
        ),
    ]
