# Generated by Django 3.2.25 on 2024-08-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0017_rename_skill_skill_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Portfolio.skill_title'),
        ),
    ]
