# Generated by Django 3.2.25 on 2024-08-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0019_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='resume')),
            ],
        ),
    ]
