# Generated by Django 3.2.25 on 2024-08-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0022_alter_project_ul_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_head_project',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
