# Generated by Django 3.2.25 on 2024-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0026_auto_20240811_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='main_head_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('moble_image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('Title', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
