# Generated by Django 3.2.25 on 2024-08-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0027_certificate_main_head_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='main_head_achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('moble_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Title', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='main_head_certificate',
            name='desk_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='main_head_certificate',
            name='moble_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='main_head_project',
            name='desk_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='main_head_project',
            name='moble_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
