# Generated by Django 3.2.25 on 2024-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0029_auto_20240811_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('paragaph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('moble_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Title', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
