# Generated by Django 3.2.25 on 2024-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0031_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Title', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
