# Generated by Django 3.2.25 on 2024-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0032_resume_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav_Headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blogs', models.BooleanField()),
                ('Resume', models.BooleanField()),
                ('Projects', models.BooleanField()),
                ('certificates', models.BooleanField()),
                ('Achievements', models.BooleanField()),
                ('contact', models.BooleanField()),
                ('search', models.BooleanField()),
            ],
        ),
    ]
