# Generated by Django 3.2.25 on 2024-08-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0033_nav_headers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nav_Headers',
            new_name='Nav_Header',
        ),
    ]
