# Generated by Django 3.2.25 on 2024-08-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0034_rename_nav_headers_nav_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_header',
            name='Title',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
