# Generated by Django 3.2.25 on 2024-08-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0035_nav_header_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
