# Generated by Django 3.2.25 on 2024-08-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0036_contact_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='email_host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_BACKEND', models.TextField()),
                ('EMAIL_HOST', models.TextField()),
                ('EMAIL_PORT', models.TextField()),
                ('EMAIL_HOST_USER', models.EmailField(max_length=254)),
                ('EMAIL_HOST_PASSWORD', models.TextField()),
                ('recive_mail_to', models.EmailField(max_length=254)),
            ],
        ),
    ]
