# Generated by Django 3.2.25 on 2024-08-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0037_contact_email_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_host',
            name='EMAIL_BACKEND',
        ),
    ]
