# Generated by Django 3.2.25 on 2024-08-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0038_remove_email_host_email_backend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_host',
            name='EMAIL_HOST',
        ),
        migrations.RemoveField(
            model_name='email_host',
            name='EMAIL_HOST_PASSWORD',
        ),
        migrations.RemoveField(
            model_name='email_host',
            name='EMAIL_HOST_USER',
        ),
        migrations.RemoveField(
            model_name='email_host',
            name='EMAIL_PORT',
        ),
    ]
