# Generated by Django 3.2.25 on 2024-08-12 10:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0039_auto_20240812_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_header',
            name='heade_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='nav_header',
            name='sidebar_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
