# Generated by Django 3.2.25 on 2024-08-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0040_auto_20240812_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nav_header',
            old_name='heade_color',
            new_name='header_color',
        ),
    ]
