# Generated by Django 3.2.25 on 2024-08-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0044_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view_imgvid_Right',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='view_imgvid_left',
            field=models.BooleanField(default=False),
        ),
    ]
